### ISSUE TITLE
I want to know how can I upload multiple files at the same time?

### ISSUE THREAD

**Issue by amormason** [betanzos/scp-upload#1]
Thank you for your this tool !
If you upload a file separately, it works well.
But I don’t know how to upload a folder, these configurations are not effective:
` source: "dist"`
` source: "./dist"`
` source: "./dist/"`
` source: "./dist/*"`

**Comment by betanzos** [comment]
> But I don’t know how to upload a folder

So far this action only works for files, but as soon as possible I add support for directories.

**Comment by amormason** [comment]
Thanks.

**Comment by betanzos** [comment]
Fixed by 6681a6d4596e23b96314c6c4ae2c154d4c4d346c, version v1.1.0
